spring:
  profiles:
    active: nonprod
server:
  port: 8080
---
spring:
  profiles: local
  kafka:
    template:
      default-topic: library-events
    producer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000
    admin:
      properties:
        bootstrap.servers: localhost:9092, localhost:9093, localhost:9094
---
spring:
  profiles: nonprod
  kafka:
    producer:
      bootstrap-servers:
        - localhost:9095, localhost:9096,  localhost:9097
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      ssl:
        trust-store-location: file:/Users/viniciuspvieira/programming/spring-kafka-api-course/ssl/client.truststore.jks
        trust-store-password: 123456
        key-store-location: file:/Users/viniciuspvieira/programming/spring-kafka-api-course/ssl/client.keystore.jks
        key-store-password: 123456
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000
        security:
          protocol: SSL
        ssl.endpoint.identification.algorithm:
---
spring:
  profiles: prod
  kafka:
    producer:
      bootstrap-servers:
        - localhost:9092, localhost:9093,  localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer

